openapi: 3.0.3
info:
  title: onecx-demo-svc API
  version: 1.0.0
servers:
 -
  url: /api
paths:
  /v1/products/{id}:
    get:
      tags:
       - products
      description: Get Product by ID
      operationId: getProductById
      parameters:
       -
        required: true
        schema:
          type: string
        name: id
        in: path
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
      security:
       - oauth2: [ ocx-demo:all, ocx-demo:read ]
  /v1/products/search:
    post:
      tags:
       - products
      description: Search products
      operationId: searchProducts
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductSearchCriteria'
      responses:
        '200':
          description: Search result for products
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Product'
                type: array
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
      security:
       - oauth2: [ ocx-demo:all, ocx-demo:read ]
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-demo:all: Grants access to all operations
            ocx-demo:read: Grants read access
            ocx-demo:write: Grants write access
            ocx-demo:delete: Grants access to delete operations
  schemas:
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    CategorySearchCriteria:
      type: object
      properties:
        pageNumber:
          format: int32
          default: 0
          type: integer
          description: The number of page.
        pageSize:
          description: The size of page
          maximum: 1000
          type: integer
          format: int32
          default: 100
        name:
          type: string
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          format: double
          type: number
        category:
          $ref: '#/components/schemas/Category'
    ProductSearchCriteria:
      type: object
      properties:
        pageNumber:
          format: int32
          default: 0
          type: integer
          description: The number of page.
        pageSize:
          description: The size of page
          maximum: 1000
          type: integer
          format: int32
          default: 100
        name:
          type: string
        price:
          format: double
          type: number
