openapi: 3.0.3
info:
  title: onecx-demo-svc API
  version: 1.0.0
servers:
 -
  url: /api
paths:
  /v1/products/{id}:
    get:
      tags:
       - products
      security:
       -
        oauth2:
         - ocx-demo:read
      operationId: getProductById
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: Product found
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Invalid request
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Product not found
      parameters:
       -
        name: id
        schema:
          type: string
        required: true
        in: path
      summary: Get Product by ID
  /v1/products/search:
    post:
      tags:
       - products
      security:
       -
        oauth2:
         - ocx-demo:read
      operationId: searchProducts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductSearchCriteria'
        required: false
      responses:
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Validation failed
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Product'
                type: array
          description: Search result for products
      summary: Search products
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-demo:all: Grants access to all operations
            ocx-demo:read: Grants read access
            ocx-demo:write: Grants write access
            ocx-demo:delete: Grants access to delete operations
  schemas:
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    CategorySearchCriteria:
      type: object
      properties:
        pageNumber:
          description: The number of page.
          type: integer
          default: 0
          format: int32
        pageSize:
          default: 100
          format: int32
          type: integer
          maximum: 1000
          description: The size of page
        name:
          type: string
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          format: double
          type: number
        category:
          $ref: '#/components/schemas/Category'
    ProductSearchCriteria:
      type: object
      properties:
        pageNumber:
          description: The number of page.
          type: integer
          default: 0
          format: int32
        pageSize:
          default: 100
          format: int32
          type: integer
          maximum: 1000
          description: The size of page
        name:
          type: string
        price:
          format: double
          type: number
