openapi: 3.0.3
info:
  title: onecx-demo-svc API
  version: 1.0.0
servers:
 -
  url: /api
paths:
  /internal/products:
    post:
      tags:
       - productsInternal
      operationId: createProduct
      summary: Create Product
      security:
       -
        oauth2:
         - ocx-demo:write
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: Product created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Validation failed
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Constraint conflict
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Internal server error
  /internal/products/{id}:
    get:
      tags:
       - productsInternal
      operationId: getProductById
      summary: Get Product by ID
      security:
       -
        oauth2:
         - ocx-demo:read
      parameters:
       -
        name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: Product found
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Invalid request
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Product not found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Internal server error
    put:
      tags:
       - productsInternal
      operationId: updateProduct
      summary: Update Product
      security:
       -
        oauth2:
         - ocx-demo:write
      parameters:
       -
        name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: Product updated
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Validation failed
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Product not found
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Optimistic lock conflict
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Internal server error
    delete:
      tags:
       - productsInternal
      operationId: deleteProduct
      summary: Delete Product
      security:
       -
        oauth2:
         - ocx-demo:delete
      parameters:
       -
        name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Product deleted
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Invalid request
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Product not found
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Constraint conflict
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Internal server error
  /internal/products/search:
    post:
      tags:
       - productsInternal
      operationId: searchProducts
      summary: Search products
      security:
       -
        oauth2:
         - ocx-demo:read
      parameters:
       -
        $ref: '#/components/parameters/limit'
       -
        $ref: '#/components/parameters/offset'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductSearchCriteria'
        required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: Search result for products
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Validation failed
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
          description: Internal server error
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-demo:all: Grants access to all operations
            ocx-demo:read: Grants read access
            ocx-demo:write: Grants write access
            ocx-demo:delete: Grants access to delete operations
  parameters:
    limit:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
      description: Maximum number of items to return
    offset:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
      description: Number of items to skip before starting to collect the result set
  schemas:
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    CategorySearchCriteria:
      type: object
      properties:
        name:
          type: string
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: double
        category:
          $ref: '#/components/schemas/Category'
    ProductSearchCriteria:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: double
